isomerpages/moe-chijsjc

_student-development/CCE/Sexuality Education.md, _useful-links/For Staff.md, resources/announcements/_posts/2023-04-06-post-Example Title.md
=> changed staff links and sed

_about-us/Our People/Non Teaching Staff.md, _about-us/Our People/School Management Team.md
Update HOD MTL surname & added new FAJT SC
=> Update HOD MTL surname & added new FAJT SC

_list-of-ccas/CentreStage (Drama & Debates).md, _list-of-ccas/Girl Guides.md, _list-of-ccas/Modern Dance.md
Have checked the CCA dates and updated
=> Have checked the CCA dates and updated

pages/Canteen Advertisement.md
=> edit the text

pages/Canteen Advertisement.md
=> update school canteen

_list-of-ccas/Angklung and Kulintang Ensemble.md, _list-of-ccas/Badminton.md, _list-of-ccas/CHIJ Youth Mission.md, _list-of-ccas/CentreStage (Drama & Debates).md, _list-of-ccas/Choir.md, _list-of-ccas/Concert Band.md, _list-of-ccas/Culinary Arts Club.md, _list-of-ccas/Fencing.md, _list-of-ccas/Girl Guides.md, _list-of-ccas/Guitar Ensemble.md, _list-of-ccas/Handbell Ensemble.md, _list-of-ccas/Modern Dance.md, _list-of-ccas/National Police Cadet Corps (NPCC).md, _list-of-ccas/Netball.md, _list-of-ccas/Pixel Playhouse.md, _list-of-ccas/Shooting.md, _list-of-ccas/Sports Club.md, _list-of-ccas/St John Brigade.md, _list-of-ccas/Table Tennis.md, _list-of-ccas/Volleyball.md
CCA Schedule & teacher-in-charge
=> CCA Schedule & teacher-in-charge 

_student-development/Digital Literacy.md
approve digital literacy - update link to PDLP resource site
=> approve digital literacy

_list-of-ccas/Netball.md
=> change salutation

_student-development/Student Conduct.md
removed religious wristband from student conduct
=> student conduct

_list-of-ccas/Pixel Playhouse.md
Tidy the table in Pixel playhouse
=> Tidy the table in Pixel playhouse

_list-of-ccas/CentreStage (Drama & Debates).md, _list-of-ccas/Concert Band.md, _list-of-ccas/Girl Guides.md
tidy CCA Achievements Table
CentreStage (Drama & Debates)
Concert Band
Girl Guides
Handbell
=> tidy CCA Achievments Table

_list-of-ccas/Choir.md
=> choir edited the year

_list-of-ccas/Choir.md
choir performance table: try again
=> choir performance table: try again

index.md
=> e-Open house site

_academic-development/Applied Subjects/Computer Applications.md, _academic-development/Applied Subjects/Design & Technology.md
=> 1024 by 786 full size dNT

_student-development/CCE/Education and Career Guidance.md
Edited table format in ECG due to the lines and dashed are seen on live website.
=> Edited table format in ECG due to the lines and dashed are seen on live website

_student-development/CCE/Education and Career Guidance.md
ECG page need to re-publish due to table dashes can be seen on live website
=> ECG page need to re-publish due to table dashes 

_useful-links/For Students.md
Updated the Link to request MIMS Password reset for students
=> Updated the Link to request MIMS Password reset for students 

_about-us/Our People/Non Teaching Staff.md
removed ai ling and added ridhwan. new ictm
=> remove staff and add

_useful-links/For Students.md
=> TT changes 08032024

_useful-links/For Students.md
Re-edit as Error 404 occured. Hopefully this time it works!
=> WA2 useful links

_about-us/Our People/Teaching Staff.md
=> Joanna Sim's email

_useful-links/For Parents.md
=> minor updates

_about-us/Our People/School Management Team.md
=> Change VP Tan's email address

_about-us/Our People/Teaching Staff.md
changed from siti_hawa_abdul_adi to siti_hawa_abdul_hadi
=> Typo on Siti Hawa Abdul Hadi email

_about-us/Our People/Non Teaching Staff.md
Added new DE to non teaching staff
=> Added new DE to non teaching staff

_about-us/Our People/Non Teaching Staff.md
=> Mr & Mrs & Mdm

_about-us/Our People/Non Teaching Staff.md
Updated of Trudy's name - Mdm Trudy Lau Chao Keng to Mdm Trudy Lau Choe Keng
Removed Ms Dhivyaa V Loganathan name
Added name of new School Counsellor - Ms Jasmine Phua Seok Ming (below Dolly)
=> Updating of SDT names.

_about-us/Our People/Teaching Staff.md
Updated Samuel email hyperlink typo. Edited email link as well.
Updated Crystal email link.
Updated both 2E FTs email linking with "mailto:"
=> Updating of e-mail links

_about-us/Our People/School Management Team.md
Updated to correct hyperlinking for school management team members.
=> School Management Team hyperlink housekeeping

_about-us/Our People/Teaching Staff.md
Updated correct email address for Veerappan.
=> Wrong email address

_academic-development/Applied Subjects/Nutrition & Food Science.md
Fixed the orientation of NFS photos
=> Minor Updates v2.0

_list-of-ccas/Netball.md, _list-of-ccas/St John Brigade.md, _list-of-ccas/Table Tennis.md
Updating of achievements for some of the CCAs.
=> CCA Updates

_the-sjc-experience/SJC 2024 Yearbook.md, _the-sjc-experience/collection.yml
added yearbook bage to sjc experience nagivation links
=> added page to sjc experience

_list-of-ccas/Choir.md
=> Choir Update

_about-us/Our People/Teaching Staff.md, _about-us/SJC Identity/School Vision and Values.md
=> Sec 1 FTs/YH/AYH

_about-us/Our People/Non Teaching Staff.md, _about-us/Our People/School Management Team.md, _about-us/Our People/Teaching Staff.md
Updated of FT/YH/AYH for Sec 3/4/5
=> Sec 3/4/5 FT

_student-development/Student Conduct.md
Changes made to Code of Conduct as requested by Gangka
=> Code of Conduct

_student-development/CCE/Education and Career Guidance.md
=> ECG Updates

_about-us/Our People/Teaching Staff.md
Updating of email for teachers
=> Email Update

_about-us/Our People/Teaching Staff.md, _list-of-ccas/Angklung and Kulintang Ensemble.md, _list-of-ccas/Badminton.md, _list-of-ccas/CHIJ Youth Mission.md, _list-of-ccas/CentreStage (Drama & Debates).md, _list-of-ccas/Choir.md, _list-of-ccas/Concert Band.md, _list-of-ccas/Culinary Arts Club.md, _list-of-ccas/Fencing.md, _list-of-ccas/Girl Guides.md, _list-of-ccas/Guitar Ensemble.md, _list-of-ccas/Handbell Ensemble.md, _list-of-ccas/Modern Dance.md, _list-of-ccas/National Police Cadet Corps (NPCC).md, _list-of-ccas/Netball.md, _list-of-ccas/Pixel Playhouse.md, _list-of-ccas/Shooting.md, _list-of-ccas/Sports Club.md, _list-of-ccas/St John Brigade.md, _list-of-ccas/Table Tennis.md, _list-of-ccas/Volleyball.md
=> Teaching Staff

_about-us/Our People/School Management Team.md
fixed daphne ang email address
=> email address fix

_student-development/CCE/Education and Career Guidance.md
=> Update of Hyperlink for ECG

_student-development/CCE/Education and Career Guidance.md
=> Update on ECG Page

_student-development/CCE/Education and Career Guidance.md
=> minor edit

_about-us/Contact Us.md
=> Fax Number

_useful-links/For Students.md
Add Internal English Oral link.
=> Examinations 

_useful-links/For Students.md
Minor changes to formatting for Internal English oral Exam 2025
=> Adding of Internal English Oral Exam 2025

_the-sjc-experience/Student Leadership Development.md
Change content of mentioned page.
=> Updates to Student Leadership Page

index.md
remove infotopic as requested by Michelle Ng
=> Remove SJC Award Infotopic
